#!/bin/bash
set -xe

mkdir -p autogenerated/wrappers/

LONGNAME=$1

SHORTNAME=$2

REPOSITORY=$3

BRANCH=$4

TYPE=$5 # biocrstudio or gxyjupyter

CONTAINER="ghcr.io/$REPOSITORY:$TYPE-$BRANCH"

cat << EOF >> "autogenerated/wrappers/$TYPE-$BRANCH.xml"
$(sed """s@##PLACEHOLDERSHORTNAME##@${SHORTNAME}@g
         s@##PLACEHOLDERLONGNAME##@${LONGNAME}@g
         s@##PLACEHOLDERCONTAINER##@${CONTAINER}@g
         s@^@      @g""" .github/scripts/templates/$TYPE_wrapper.xml)
EOF
