#!/bin/bash
set -xe

mkdir -p autogenerated/wrappers/

LONGNAME=$1

SHORTNAME=$2

REPOSITORY=$3

BRANCH=$4

RSTUDIOCONTAINER="ghcr.io/$REPOSITORY:biocrstudio-$BRANCH"
JUPYTERCONTAINER="ghcr.io/$REPOSITORY:gxyjupyter-$BRANCH"

cat << EOF >> "autogenerated/wrappers/biocrstudio-$BRANCH.xml"
$(sed """s@##PLACEHOLDERSHORTNAME##@${SHORTNAME}@g
         s@##PLACEHOLDERLONGNAME##@${LONGNAME}@g
         s@##PLACEHOLDERCONTAINER##@${RSTUDIOCONTAINER}@g
         s@^@      @g""" .github/scripts/templates/rstudio_galaxy_wrapper.xml)
EOF

cat << EOF >> "autogenerated/wrappers/gxyjupyter-$BRANCH.xml"
$(sed """s@##PLACEHOLDERSHORTNAME##@${SHORTNAME}@g
         s@##PLACEHOLDERLONGNAME##@${LONGNAME}@g
         s@##PLACEHOLDERCONTAINER##@${JUPYTERCONTAINER}@g
         s@^@      @g""" .github/scripts/templates/jupyter_galaxy_wrapper.xml)
EOF
