name: Generate Galaxy wrappers
on:
  workflow_dispatch:
    inputs:
      longname:
        description: "Long Name (eg: Multiplex Imaging with Bioconductor's OSN)"
        required: true
      shortname:
        description: 'Short Name (eg: OSN_Multiplex)'
        required: true

jobs:
  generatewrappers:
    name: Generate Galaxy wrappers for RStudio and Jupyter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -x
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          LONGNAME=${{ github.event.inputs.longname }}
          SHORTNAME=${{ github.event.inputs.shortname }}
          REPOSITORY=${{github.repository}}
          BRANCH=${GITHUB_REF#refs/heads/}

          bash generate_wrappers.sh $LONGNAME $SHORTNAME $REPOSITORY $BRANCH
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated Galaxy wrappers on $(echo $(date +'%m-%d-%y-%H-%M-%S'))"
          git push
